import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components";


export const metadata: Metadata = {
  title: "Pet Hospital App",
  description: "Generated by pet hospital app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
